name: CI

on: push

defaults:
  run:
    working-directory: ./../../../maquetando-la-web-decodely

jobs:
  lint:
    runs-on: ubuntu-latest
    name: 🚀 Lint
    timeout-minutes: 15

    steps:
      - name: 👍 Checkout
        uses: actions/checkout@v2

      - name: 📥 Install Dependencies
        run: yarn install

      - name: 💅 Lint
        run: yarn lint

      - name: ✅ Design System - Unit tests
        run: yarn design-system:test
